//User Types
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_NEW_USER = 'SET_NEW_USER';

//Property Types
export const SET_ERRORS = "SET_ERRORS";
export const PROPERTY_LOADING = "PROPERTY_LOADING";
export const SET_PROPERTIES = "SET_PROPERTIES";
export const SET_TOTAL_PROPERTIES = "SET_TOTAL_PROPERTIES";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";

//Agency Types
export const SET_AGENCY = 'SET_AGENCY';
export const AGENCY_LOADING = 'AGENCY_LOADING';
export const SET_AGENCY_ERRORS = 'SET_ERRORS';
export const CLEAR_AGENCY_ERRORS = 'CLEAR_AGENCY_ERRORS';

//Add Properties
export const ADD_PROPERTY = 'ADD_PROPERTY';
export const PROPERTY_SERVER_UPLOAD = 'PROPERTY_SERVER_UPLOAD';
export const PROPERTY_UPLOADING = 'PROPERTY_UPLOADING';
export const PROPERTY_SERVER_UPLOAD_ERROR = 'PROPERTY_SERVER_UPLOAD_ERROR';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';

//Add Properties
export const SET_CATEGORY = 'SET_CATEGORY';

//Reset redux state
export const RESET = 'RESET';

//Admin Dashboard
export const AGENCIES = 'AGENCIES';
export const AGENCIES_LOADING = 'AGENCIES_LOADING';
export const APPROVAL_PROCESSING = 'APPROVAL_PROCESSING';

//Agency Profile Setup
export const SAVING_AGENCY_PROFILE = 'SAVING_AGENCY_PROFILE';
export const HAS_AGENCY = 'HAS_AGENCY';

//Bookmark Property
export const SET_BOOKMARKED_PROPERTIES_ERRORS = 'SET_BOOKMARKED_PROPERTIES_ERRORS';
export const SET_BOOKMARKED_PROPERTIES = 'SET_BOOKMARKED_PROPERTIES';
export const BOOKMARKED_PROPERTIES_LOADING = 'BOOKMARKED_PROPERTIES_LOADING';
export const SAVING_BOOKMARKED_PROPERTY = 'SAVING_BOOKMARKED_PROPERTY';

//Agencies Property
export const SET_AGENCY_PROPERTIES = 'SET_AGENCY_PROPERTIES';
export const AGENCY_PROPERTIES_LOADING = 'AGENCY_PROPERTIES_LOADING';
export const SET_AGENCY_PROPERTIES_ERRORS = 'SET_AGENCY_PROPERTIES_ERRORS';

//Property Pagination
export const NEXT_PROPERTIES = 'NEXT';
export const PREVIOUS_PROPERTIES = 'PREVIOUS';
